### ISSUE TITLE
Proszę o kontakt

### ISSUE THREAD

**Issue by codecleaner** [azawlocki/azawlocki.github.io#1]
Dzień dobry,

bardzo cieszę się, że prowadzi Pan Code Club i nie znalazłem innego sposobu (szkoła nie odpowiada na maile), więc proszę o kontakt. :)

Pozdrawiam,
Wojtek Zieliński

Code Club Polska

**Comment by azawlocki** [comment]
Dzień dobry,

ja też się cieszę z tego powodu :)
Napiszę kilka słów o klubie dziś wieczorem.

Pozdrawiam,
Artur Zawłocki

**Comment by azawlocki** [comment]
Kilka słów o klubie: wystartowaliśmy pod koniec października 2015 w szkole
podstawowej nr 52 w Warszawie, ja jestem jedynym prowadzącym a dzieci na
zajęciach jest w porywach 12, a zwykle 9-10. To są 9-latki z klasy 3 (w tym
mój syn). Zajęcia mamy teoretycznie co tydzień w soboty o 9.00, ale czasem
coś wypada (próbne egzaminy szóstoklasistów, święta, itp.) więc wychodzą
2-4 spotkania w miesiącu.

Przerabiamy kurs scratcha z codeclub.org.pl, aktualnie robimy drugi projekt
z Semestru 2 (w międzyczasie był jakiś projekt archiwalny i projekty
okolicznościowe typu kartka świąteczna), zwykle jeden projekt robimy na
dwóch spotkaniach.

Ten pierwszy rok klubu traktuję trochę jako próbę, ale już widać, że się
udało i prawie na pewno będziemy kontynuować po wakacjach, a może nawet uda
się znaleźć czas, lub zrekrutować nowych ochotników, żeby powstała druga
grupa.

Tyle o naszym klubie. W sumie nie wiem nawet, czy istnieją jakieś fora,
polskie albo światowe, do wymiany doświadczeń klubowych?

Pozdrawiam
Artur

**Comment by codecleaner** [comment]
Przepraszam, zapomniałem podać maila kontaktowego: wojtek.zielinski@codeclub.org.pl. Proszę o kontakt na ten adres - postaram się odpisać, myślę, że będzie łątwiej niż przez publiczne issue na githubie :)

Wojtek
